### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ecervac** [faktiva/prestashop-seo-tk#57]
Hello,
I uploaded the module, but can't neither install it nor delete it from module manager.
If i delete, manager tells that module successfully deleted, but it still appears in the list.
If I want to install it, a get: You do not have the rights to update the faktiva-seo-tk module. Please make sure you are logged in to the PrestaShop Addons account that purchased the module.
I tried both logged in and not logged in PrestShop Addons.
PS version is 1.6.1.4
PHP version is 5.6.26

Please suggest how to fix.
Thank you.

**Comment by drAlberT** [comment]
Hi,
  it should be an issue with the name change of the module ...

Please give me some more info:

- do you installed the module now or you have upgraded from the "old" `zzSEOtk`?
- are you installing the [.ZIP](https://github.com/faktiva/prestashop-seo-tk/releases/download/1.4.0/faktiva_seo_tk.zip) file being attached to the release or are you trying to install something different (from sources, from *master* branch, whatever else) ?
- It would be possible to have an access to inspect your situation?
- Please try to edit `config.xml` and replace dashes with underscores in the module name.
   `faktiva-seo-tk` -> `faktiva_seo_tk`

Waiting for your reply, thanks

**Comment by drAlberT** [comment]
@ecervac please try version [1.4.1](https://github.com/faktiva/prestashop-seo-tk/releases/tag/1.4.1)

**Comment by ecervac** [comment]
Hello,1.4.1 installed and works good.No more problems.Thank you very very much for the support.Are you guys going to implement also rel="next/prev" tags?I'm afraid all my paginated content will be ignored after page 1.
Regards,Eugen

**Comment by drAlberT** [comment]
@ecervac Nice to know it works :) Forgot a rename in the first release, sorry.


Next/prev should already work, depending on you theme implementation, as the canonical URL takes pagination into account (i.e. `/category/?p=2`is visible to the crawlers) ... 

Just disable JS in your browser and inspect the source code while navigating your shop .. you should see the canonical meta-tag to behave the right way ..

Going to close this issue. Thanks for your feedback, please take the time to report on the forum too ;)


Regards
