### ISSUE TITLE
Fix composer prestashop-module support

### ISSUE THREAD

**Issue by numanWD** [faktiva/prestashop-seo-tk#61]
Hi

The new prestashop modules can be installed using composer.

To achieve that the module should be in the root of the repo.

Otherwise (now) when it is installed it is created an extra subfolder.

You can see an example in some officials modules:

``https://github.com/PrestaShop/ps_banner``

Thanks for your module

**Comment by drAlberT** [comment]
Hi @numanWD ,
  thanks for reporting .. good catch

**Comment by drAlberT** [comment]
@numanWD could you try https://github.com/faktiva/prestashop-seo-tk/tree/fix-ps-composer-support ?

**Comment by numanWD** [comment]
I have done a small PR in your branch

**Comment by drAlberT** [comment]
Please change it to remove the camelcase and leave the for name readable so I can merge it

Thanks a lot
