### ISSUE TITLE
Add a custom canonical url feature

### ISSUE THREAD

**Issue by rauloliv** [faktiva/prestashop-seo-tk#65]
For stores with discontinued and very similar products a custom canonical url pointing to the new/alternative product would be good.

Thank you.

**Comment by drAlberT** [comment]
Yes it would :) .. maybe in the future .. no time now for new features, sorry.

But anybody having the necessary skills feel free to contribute such an enhancement.

Thanks @rauloliv

**Comment by drAlberT** [comment]
The requested behavior is already be possible in the Product page, in the backoffice:

![screenshot_20170509_232345](https://cloud.githubusercontent.com/assets/1442700/25873445/de9dc438-350e-11e7-9963-18e3dbab2ba0.png)


Though this would be behind the scope of this module .. IIRC there are other modules doing this job ..
