### ISSUE TITLE
Problem When is enabled "Accented URL"

### ISSUE THREAD

**Issue by Raito00** [faktiva/prestashop-seo-tk#66]
When "Accented URL" is enabled not adding hreflang in header
On PS is two languages: English and Swedish
on English all working as should but on Swedish where on friendly url is Swedish letters: "äåö" module not add hreflang in header.

Shop runs:
PS 1.6.1.11
php7.0

Thanks!

**Comment by Raito00** [comment]
I can give access to my server to test special character "äåö" issue in links.

**Comment by drAlberT** [comment]
Sure, send it to prestashop-seo-tk@faktiva.com

thanks

**Comment by Raito00** [comment]
"canonical" link is generated on links with char "äåö"

but not "alternate" links :(

**Comment by Raito00** [comment]
@drAlberT - Did You have  time to look on Test server ?

**Comment by drAlberT** [comment]
Will dedicate an hour tomorrow morning

**Comment by drAlberT** [comment]
Is it working now?

**Comment by Raito00** [comment]
Hreflang not working when selected Swedish language!

**Comment by drAlberT** [comment]
I have posted on the wrong module .. I was talking about clean urls ..

**Comment by drAlberT** [comment]
Found the issue .. working on ..

**Comment by drAlberT** [comment]
should be fixed .. please confirm

**Comment by Raito00** [comment]
Yes!
Working now!

P.S.
In my case only one problem with simple blog hreflang. There is some "Simple Blog" module bug with url rewrite because it take all links from active language ..

**Comment by drAlberT** [comment]
Yes there are other issue with that module opened ...
