### ISSUE TITLE
canonical url remove "?p=2" from next page

### ISSUE THREAD

**Issue by Raito00** [faktiva/prestashop-seo-tk#69]
Hi!
If i think right canonical url on next page it should be the same like first one.

example.com/modules 
example.com/modules?p=2
example.com/modules?p=3
so on ...

canonical url on all this pages should be: example.com/modules

I`m right or wrong ?

**Comment by drAlberT** [comment]
Hi,
  thank you for writing.

If the content on two pages is different then you should have a canonical URL for each different page .. 
AFAIK pagination (with JS disabled) leads to different pages (different contents), so you should be wrong ;)

If you still think it should be an issue feel free to reopen.

Best regards

**Comment by Raito00** [comment]
Thanks! Now its clear! :)
