### ISSUE TITLE
hreflang - Use iso_code instead of language_code

### ISSUE THREAD

**Issue by GuillaumeG22** [faktiva/prestashop-seo-tk#75]
Hello,

Prestashop does not manage differences between countries and languages in the data structure.
I recommend using the iso code instead of the language_code.

This problem has been confirmed by an SEO expert.

**Comment by drAlberT** [comment]
Please provide some links to resources defending this thesis :)

**Comment by GuillaumeG22** [comment]
Hello,

For only 1 language, there may be several IETF code (see http://www.lingoes.net/en/translator/langcode.htm).
For the French language, for example, there are also the Belgians, the Swiss, the Canadians ... who are concerned.

If you specify the IETF code instead of the ISO code (2 characters), the Belgians and Swiss will not be affected by this hreflang from Google whereas it is the same French language.
There is also this article that allows to use the ISO code: https://support.google.com/webmasters/answer/189077?hl=en

In Prestashop, it is not possible to associate multiple IETF codes with 1 language.

Do you understand what I'm getting at?

Guillaume

**Comment by drAlberT** [comment]
I know the concepts you reported, yes I understand :)

My point is that one could create two shops, having the same language but addressing different localisations (say en_US and en_UK) with the target of distributing different contents, currencies, etc for different geographic areas .. 

I think this should be possible in PS .. and for this reason I'd like to leave the opportunity of use the language_code .. 

As said in the PR review, will be simple to explode by the "_" and retain only the language ISO code in the view, leaving the controller to provide the more "complete" information ..

Hope to have been explained :)

**Comment by drAlberT** [comment]
As stated in the second article you cite

> Supported language values
> The value of the hreflang attribute identifies the language (in ISO 639-1 format) and optionally the > region (in ISO 3166-1 Alpha 2 format) of an alternate URL. For example:
> 
> de: German content, independent of region
> en-GB: English content, for GB users
> de-ES: German content, for users in Spain

This is already the actual behavior of this module.
