### ISSUE TITLE
hrflag missing for images

### ISSUE THREAD

**Issue by medinetclinic** [faktiva/prestashop-seo-tk#79]
Hello,
After install your module I check my site with screeming frog seo, and I see hrflag is ok for all pages but I see missing the product images.
Also Google web master say the same.
I think this is important.

**Comment by drAlberT** [comment]
Hi, thanks for reporting.

Can you give more details / references to this?

**Comment by medinetclinic** [comment]
First give you thanks for this ... very good module.
As I told you after check with screaming frog seo spider, I see all pages has hrflag but the module missing this tag, or after install it, it do not implement the tag in my installed images.
My site is https://automatic-pill-dispenser.com
Attache you will fing an screen capture of it.
![captura1](https://user-images.githubusercontent.com/23633558/31375334-78968236-ada1-11e7-8bd0-6ee7436ff04a.jpg)
Also webmaster say the same

Regards

**Comment by drAlberT** [comment]
Yes I got the point, what I miss is how you think my module could address this ..  How can I know if you have localized images on your server?

That warning is telling you that your images lack of "translations", i.e. you havent provided a img_a-en.jpg, then a img_a-es.jpg and so on .. if you would have such kind of images (for every image, product, category, cms, and layout) then maybe one can find a way to insert hreflang into img tag too ...


If I am missing the point plz link me to some official documentation about what you expect to be the right result.. I searched a bit on google with no luck

**Comment by medinetclinic** [comment]
Dear Albert,
I see you have connected at 16h07 and see the main url
http://automatic-pill-dispenser.com/en/
But all the images concerning modules are restricted by my robot.txt
I try to coment with you, product images.
I understand what you say, you (your module) have no way to know what modules I have running ... so on
But your module will have to know every PS has product images, also what tpl(s) has product images to link.
So if you check the product page in your language:
https://automatic-pill-dispenser.com/en/home/automatic-pill-dispenser.html

There you can see there, there are 7 product images, same for all languages, but with a link for every language. If you choose DE language, the image link will have a link name in german.
The matter is, do the product images need an hreflang ... because the only way Google know what iamages are for each language is trough the language sitemap.

If you think this is not neccesary I acept it and that´s all.
I am happy with your module and your collabotarion.
Regards.

**Comment by drAlberT** [comment]
Uhmm .. I think you are misinterpreting the href-lang .. maybe I'm wrong, so - again - if you have a doc for this case plz point me to it.

My interpretation is that whenever you have an hreflag you *have* to provide, on the same page, links to every other hreflangs. If you take a look to the language selection dropdown code it behaves this way.

So, if you add an hreflang to img_a.jpg, then you have to add in the same page (and probably you'd want to hide them to the user) links to "localized" versions of the image.

Are you sure an explicit "lang" attribute would not be a better choice?

Please understand I don't want to discard your issue, simply I'm not sure of your proposed solution.
![screenshot_20171011_090754](https://user-images.githubusercontent.com/1442700/31426711-c1e2d228-ae64-11e7-8761-0972fd0645e7.png)

**Comment by medinetclinic** [comment]
Dear Dr. Albert,
Could be you are right.
Also I am not quite sure about this because it is confussed.
We must lost this issue. Thanks for all.

**Comment by metacreo** [comment]
:) this issue related to SEO Sider or another "SEO optimizers" who report bullshit like this ))). All ok with images. Nice module. Do not pay attention, and forget this issue.
