### ISSUE TITLE
redirect to 500 error

### ISSUE THREAD

**Issue by medinetclinic** [faktiva/prestashop-seo-tk#80]
Dear DrAlbert,

I've been working with the module for several weeks, but the other day I went to the webmaster and found that I had a lot of errors 500
After investigating several hours it occurred to me to deactivate his module and I discovered that he was the cause of the 500 errors

The issue is the following .... if I invented an url finished in html and the module is activated it results in error 500, if I deactivate it, the 500 error disappears and it shows a product page not found.

To check this my store is at: https://automatic-pill-dispenser.com
once in the store if I put a URL like stupidity.html ... the resault is error 500 instead of page not found.

But if I disable Faktiva, the 500 error disappears

a greeting

**Comment by drAlberT** [comment]
Hi,
 please provide your URL rewriteing configuration

**Comment by medinetclinic** [comment]
Hi,
I see yesterday around 19:00 you connected with my web and check /en/drAlbert.htm and *.htmx ... drirecto to page not found..... RIGHT
But when you put /en/drAlberet.html .... direct to 500 error

AS I told you this is only with a sillyURL.html .... it means not belongs to the shop or none product has this url

My rewrite for ptoducts is: {category:/}{rewrite}.html .... I am ussing a rewrite module called prettyURL

Concerning php error ..... no information about that.

Regards

**Comment by drAlberT** [comment]
Can't help without logs .. blind investigation is out of my powers ;)

Anyway, I have an URL rewrite (free) module too .. you could try it, it should work fine

**Comment by drAlberT** [comment]
@medinetclinic .. ping

**Comment by medinetclinic** [comment]
Hello,
I am still having the same problema but as all other is working well I have decide to maintein your module on, it is a nice one.
I know it is something related my rewrite module prettyURL .. it give me problems from time to time...
With time I will use your rewrite module but now I am concentred in other matters.

Thanks for your support.
