### ISSUE TITLE
nofollow on categories

### ISSUE THREAD

**Issue by Rzeszow** [faktiva/prestashop-seo-tk#84]
@drAlberT 
Is it normal that there are `noindex` and `nofollow` on the category page?

**Comment by Rzeszow** [comment]
Is it about this line in the _header.tpl_ file?
```
<meta name="robots" content="{if isset($nobots)}no{/if}index,{if isset($nofollow) && $nofollow}no{/if}follow" />
```
When I delete it, I have no attributes (No)Index on any page.

**Comment by drAlberT** [comment]
Of course... but the right question is why the variables in that line are
valorized for your category page ...

They shouldn't

**Comment by Rzeszow** [comment]
I do not know myself. Everything I checked should not be like this.
Prestashop 1.6.1.18

**Comment by drAlberT** [comment]
Solved?

**Comment by Rzeszow** [comment]
Yes, but only by changing the code to the above one. This is probably the error of any module or Prestashop itself.

**Comment by Rzeszow** [comment]
I know why. Let's say that we have a category and it has subcategories then in this main category there are set "nofollow" and "noindex". But in these subcategories everything is fine.
